name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    permissions:
      id-token: write
      pages: write

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # # Cache
      # - uses: actions/cache@v3
      #   with:
      #     path: Library
      #     key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
      #     restore-keys: |
      #       Library-

      # Test
      #      - name: Run tests
      #        uses: game-ci/unity-test-runner@v4
      #        env:
      #          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_FILE }}
      #          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #        with:
      #          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      # - name: Build project
      #   uses: game-ci/unity-builder@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: schmuild

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: copy vercel.json to correct place
        run: cp vercel.json schmuild/WebGL/WebGL/vercel.json

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }} ./schmuild/WebGL/WebGL --yes

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'schmuild/WebGL/WebGL'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
